version: '3.8'

services:
  webapi:
    image: mcr.microsoft.com/devcontainers/dotnet:8.0
    volumes:
      - ../../backend:/workspace/backend:cached
      - ../../frontend:/workspace/frontend:cached
    ports:
      - "5050:5000"
      - "5051:5001"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: sleep infinity

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
