### YamlMime:ManagedReference
items:
- uid: ViaTabloidApi.Infrastructure.Configuration
  commentId: N:ViaTabloidApi.Infrastructure.Configuration
  id: ViaTabloidApi.Infrastructure.Configuration
  children:
  - ViaTabloidApi.Infrastructure.Configuration.StoryConfiguration
  langs:
  - csharp
  - vb
  name: ViaTabloidApi.Infrastructure.Configuration
  nameWithType: ViaTabloidApi.Infrastructure.Configuration
  fullName: ViaTabloidApi.Infrastructure.Configuration
  type: Namespace
  assemblies:
  - ViaTabloidApi
references:
- uid: ViaTabloidApi.Infrastructure.Configuration.StoryConfiguration
  commentId: T:ViaTabloidApi.Infrastructure.Configuration.StoryConfiguration
  href: ViaTabloidApi.Infrastructure.Configuration.StoryConfiguration.html
  name: StoryConfiguration
  nameWithType: StoryConfiguration
  fullName: ViaTabloidApi.Infrastructure.Configuration.StoryConfiguration
