name: Build and Push Docker Images After PR Merge

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set lowercase repository owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Cache Docker layers for backend
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-backend
          key: docker-backend-cache-${{ github.base_ref }}-${{ github.sha }}
          restore-keys: |
            docker-backend-cache-${{ github.base_ref }}-
            docker-backend-cache-

      - name: Cache Docker layers for frontend
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-frontend
          key: docker-frontend-cache-${{ github.base_ref }}-${{ github.sha }}
          restore-keys: |
            docker-frontend-cache-${{ github.base_ref }}-
            docker-frontend-cache-

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/ViaTabloidApi
          file: ./backend/ViaTabloidApi/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/viatabloid/backend:latest
            ghcr.io/${{ env.REPO_OWNER_LC }}/viatabloid/backend:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache-backend
          cache-to: type=local,dest=/tmp/.buildx-cache-backend,mode=max

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/viatabloid/frontend:latest
            ghcr.io/${{ env.REPO_OWNER_LC }}/viatabloid/frontend:${{ github.sha }}
          build-args: |
            VITE_API_HOST=localhost
            VITE_API_PORT=5001
          cache-from: type=local,src=/tmp/.buildx-cache-frontend
          cache-to: type=local,dest=/tmp/.buildx-cache-frontend,mode=max

      - name: Output published images
        run: |
          echo "Published backend image: ghcr.io/${{ env.REPO_OWNER_LC }}/viatabloid/backend:latest"
          echo "Published frontend image: ghcr.io/${{ env.REPO_OWNER_LC }}/viatabloid/frontend:latest"