name: Build and Cache Docker Images

on:
  push:
    branches: [ main, dev, feature/** ]
    paths:
      - 'backend/ViaTabloidApi/**'
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/ViaTabloidApi/**'
      - 'frontend/**'

permissions:
  contents: read

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers for backend
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-backend
          key: docker-backend-cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            docker-backend-cache-${{ github.ref }}-
            docker-backend-cache-

      - name: Build backend Docker image (cache only)
        uses: docker/build-push-action@v5
        with:
          context: ./backend/ViaTabloidApi
          file: ./backend/ViaTabloidApi/Dockerfile
          push: false
          tags: viatabloid-backend:cache
          cache-from: type=local,src=/tmp/.buildx-cache-backend
          cache-to: type=local,dest=/tmp/.buildx-cache-backend,mode=max

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers for frontend
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-frontend
          key: docker-frontend-cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            docker-frontend-cache-${{ github.ref }}-
            docker-frontend-cache-

      - name: Build frontend Docker image (cache only)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: viatabloid-frontend:cache
          build-args: |
            VITE_API_HOST=localhost
            VITE_API_PORT=5001
          cache-from: type=local,src=/tmp/.buildx-cache-frontend
          cache-to: type=local,dest=/tmp/.buildx-cache-frontend,mode=max