name: Build and Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Install DocFX
        run: |
          dotnet tool install -g docfx
      - name: Build Docs
        run: |
          docfx docs/docfx.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
